### ISSUE TITLE
Conflict with new version of uEssentials Plugin

### ISSUE THREAD

**Issue by SNiiPz** [Sadusko/Death-Messages#20]
uEssentials plugin just update to the version 1.2.1.0 and when we have the 2 plugins, DeathMessages and uEssentials in a server, it shows the deathmessage when someone die but after that it shows a error message on the chat too saying something like : " Lang: Key not found 'DEATH_SUICIDE". If it's possible to update the plugin to stop this conflict between this 2 awesome plugins would be perfect!

**Comment by Sadusko** [comment]
I am not updating DeathMessages anymore, therefore you could ask the owner of uEssentials to modify his plugin.
