### ISSUE TITLE
Error on Latest Deathmessage version(02/3/2016)

### ISSUE THREAD

**Issue by jorea143** [Sadusko/Death-Messages#3]
[Error] InvalidOperationException: <DMC xmlns=''> was not expected - System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot (System.Xml.Serialization.XmlTypeMapping rootMap)
System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot ()
System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.Serialization.XmlSerializationReader reader)
Rethrow as InvalidOperationException: There is an error in XML document.
System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.Serialization.XmlSerializationReader reader)
System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader)
System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader)
Rocket.Core.Assets.XMLFileAsset`1[DeathMessages.DMC2].Load (Rocket.Core.Assets.AssetLoaded`1 callback, Boolean update)
Rethrow as Exception: Failed to deserialize XMLFileAsset: Plugins/DeathMessages/DeathMessages.configuration.xml
Rocket.Core.Assets.XMLFileAsset`1[DeathMessages.DMC2].Load (Rocket.Core.Assets.AssetLoaded`1 callback, Boolean update)
Rocket.Core.Assets.XMLFileAsset`1[DeathMessages.DMC2]..ctor (System.String file, System.Type[] extraTypes, DeathMessages.DMC2 defaultInstance)
Rocket.Core.Plugins.RocketPlugin`1[TConfiguration].LoadPlugin ()
Rocket.Core.Plugins.RocketPlugin.OnEnable ()
UnityEngine.GameObject:.ctor(String, Type[])
Rocket.Core.Plugins.RocketPluginManager:loadPlugins()
Rocket.Core.Plugins.RocketPluginManager:Start()

**Comment by Sadusko** [comment]
Remove the old configuration. Set it up again.
